formatter: "markdown table"

version: ""

header-from: "docs/header.md"
footer-from: ""

recursive:
  enabled: false

sections:
  show:
    - header
    - providers
    - resources
    - requirements
    - inputs
    - outputs

content: |-
  {{ .Header }}
  {{ include "docs/task.md" }}
  {{ include "docs/solution.md" }}
  ### Reference
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
  ### Results
  {{ include "docs/results.md" }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->


output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 4
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
