# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
/*   backend "s3" {
    bucket         = "its-week1-task3-00"
    key            = "terraform.tfstate"
    region         = "us-east-1"  # Update with your desired region
    encrypt        = true
    dynamodb_table = "terraform-lock"
  }
 */
  backend "local" {
    
  }
 }
