repositories:
  - name: k8s
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: sigs 
    url: https://kubernetes-sigs.github.io/metrics-server    

releases:
  # ------------------------- Cert-manager 
  - name: cert-manager
    chart: jetstack/cert-manager
    version: "v1.13.2"
    namespace: cert-manager
    createNamespace: true
    # Installing CRDs is vital for the cert-manager
    set:
      - name: installCRDs
        value: true

  # ------------------------- Ingress Nginx
  - name: ingress-nginx
    chart: k8s/ingress-nginx
    namespace: ingress-nginx
    createNamespace: true
    # The hook polls the cluster until the ingress external IP has been assigned
    # Than it writes the IP into variables file for the further using by django chart
    hooks:
      - events: 
        - postsync
        showlogs: true
        command: "/bin/bash"
        args: ["-c", "./get-lb-ip.sh"]    

  # ------------------------- HPA Metrics Server
  #- name: hpa-metrix
  #  chart: sigs/metrics-server
  #  namespace: metrics-server
  #  createNamespace: true
  #  version: "3.11.0"

  # ------------------------- Django sample application
  - name: django-app
    chart: ./django-app
    version: "0.1.1"
    namespace: django-app
    createNamespace: true
    values:
      - django-app/values.yaml
      - lb-ip.yaml
    secrets:
      - "django-app/db-url-secrets.yaml"
      - "django-app/dyn-dns-passw-secrets.yaml"
    # cert-manager and ingress-nginx charts should be installed before the application  
    needs:
      - cert-manager/cert-manager
      - ingress-nginx/ingress-nginx
      #- metrics-server/hpa-metrix

# ---------------------------- Helm settings
# Set timeouts for the Job which checks that the ingress IP is accessable 
# by the application FQDN
helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 1800
