apiVersion: v2
name: Django-app-chart
description: A Helm chart for Kubernetes
type: application

version: "0.1.1"
appVersion: "0.2.1"

keywords:
  - django
  - lets-encrypt
  - ingress-nginx
home: https://github.com/dmytro108/itsynd/tree/master/week7-Kubernetes/task1

maintainers:
  - name: Dmitry Fedunets
    email: dmitry.fedunets@gmail.com
    url: https://github.com/dmytro108/
