# Application config
Config:
  host: week7.fedunets.uk
  dyn_dns_endpoint: "https://dynamicdns.park-your-domain.com/update?"

# App's container properties
Container:
  version: latest
  port: 8000
  resources:
    cpu:
      req: 400m
      lim: 500m
    memory:
      req: 200Mi
      lim: 512Mi

# The app pods replicas number. 
# Used in Pod Deployment and Pod Autoscaling 
Deployment:
  replicas:
    min: 2
    max: 6

# Pod Autoscaling thresholds for CPU and Memory utilization
HPA:
  target:
    cpu: 50
    memory: 80


# application Service port
Service:
  port: 8080

# Lets Encrypt registration data
TLS:
  mail: dmitry.fedunets@gmail.com

# Ingress paths

IngressPaths:
- name: app
  path: /
  backend:
    service:  public-app
    port: 8080
- name: static
  path: /static
  backend:
    service: static-web-server
    port: 8888