apiVersion: v2
name: Djang-app-ingress
description: A Helm chart for Kubernetes
type: application

version: "0.1.1"
appVersion: "0.2.1"

keywords:
  - django
  - lets-encrypt
  - ingress-nginx
home: https://github.com/dmytro108/itsynd/tree/master/week7-Kubernetes
maintainers:
  - name: Dmitry Fedunets
    email: dmitry.fedunets@gmail.com
    url: https://github.com/dmytro108/

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    alias: app-ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
