kind: Deployment
apiVersion: apps/v1

metadata:
  name: sample-app
  namespace: {{ .Release.Name}}
  labels:
    app: django-sample

spec:
  replicas: {{ .Values.Deployment.replicas.min }}

  selector:
    matchLabels:
      app: django-sample

  template:
    metadata:
      namespace: {{ .Release.Name}}
      labels:
        app: django-sample

    spec:
      restartPolicy: Always

      containers:
        - name: django-app
          image: {{ print .Values.image.repository ":" .Values.image.tag }}
          # ------------ Resources
          resources:
            requests:
              cpu:  {{ .Values.Container.resources.cpu.req }}
              memory: {{ .Values.Container.resources.memory.req }}
            limits:
              cpu: {{ .Values.Container.resources.cpu.lim }}
              memory: {{ .Values.Container.resources.memory.lim }}
          # ------------ Config
          envFrom:
          - secretRef:
              name: db-credentials
          - configMapRef:
              name: db-config
          env:
            - name: DATABASE_URL
              value: "$(DB_SCHEMA)://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST).$(DB_SCHEMA).svc.cluster.local:$(POSTGRES_PORT)/$(POSTGRES_DB)"
            - name: DJANGO_ALLOWED_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: django-app-conf
                  key: allowed_host
          ports:
            - containerPort: {{ .Values.Container.port }}
              protocol: TCP
              name: django-port
          # -------------- Helth check
          readinessProbe:
            httpGet:
              path: /
              port: django-port
              httpHeaders:
                - name: Host
                  value: {{ .Values.Config.host }}
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: django-port
              httpHeaders:
                - name: Host
                  value: {{ .Values.Config.host }}
            initialDelaySeconds: 5
            periodSeconds: 10
          # ---------------- Security
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - NET_RAW
                - ALL
