{{- include "default-deny.npol" . | nindent 0 }}

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-from-ingress
  namespace: {{ .Release.Name }}
spec:
  policyTypes:
    - Ingress

  podSelector: {}
  
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-to-db
  namespace: {{ .Release.Name }}
spec:
  policyTypes:
    - Egress

  podSelector:
    matchLabels:
        app: sample-app
  
  egress:
    - to:
      - podSelector:
            matchLabels:
              tier: db

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-to-github
  namespace: {{ .Release.Name }}
spec:
  policyTypes:
    - Egress

  podSelector:
    matchLabels:
      app: static-web
  
  egress: 
    - {}
