kind:       Deployment
apiVersion: apps/v1

metadata:
  name:      sample-app
  namespace: django-app
  labels:
    app:     django-sample

spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-sample
  template:
    metadata:
      namespace: django-app
      labels:
        app:     django-sample
    spec:
      containers:
      - name:  django-app
        image: registry.digitalocean.com/sample-django-app/app:latest
        resources:
          requests:
            cpu:    100m
            memory: 100Mi
          limits:
            cpu:    100m
            memory: 100Mi
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: app-conf
              key:  db_connection
        ports:
        - containerPort: 8000
          protocol:      TCP
          name:          django-port
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot:             true
          runAsUser:                999
          capabilities:
            drop:
            - NET_RAW
            - ALL

      restartPolicy: Always
