- name: Install pip
  become: true
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Install acl # Needed for acting Ansible on bahalf of postgres user
  become: true
  ansible.builtin.dnf:
    name: acl
    state: present

- name: Install psycopg2 # Needed for Ansible PostgreSQL module
  become: true
  become_user: postgres
  ansible.builtin.pip:
    name: psycopg2-binary
    executable: pip3
