- name: Install pip
  become: true
  ansible.builtin.dnf:
    name:
      - python3-pip
      - python3-psycopg2
      - acl # Needed to allow Ansible acting on behalf of postgres user
    state: present
