---
# ************************************** Install PostgreSQL & Python libs
- ansible.builtin.include_tasks: inst_prerequisites.yml

- ansible.builtin.include_tasks: inst_postgres.yml

# ************************************** PostgreSQL Up & Run
- ansible.builtin.include_tasks: run_postgres.yml

# ************************************** DB Setup
- ansible.builtin.include_tasks: new_db.yml
- ansible.builtin.include_tasks: new_user.yml
- ansible.builtin.include_tasks: user_privs.yml
