kind: Issuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-prod
  namespace: {{ .Release.Name }}

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.TLS.mail }}
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx

