# Persistance volume claim for static assets filles
kind: PersistentVolumeClaim
apiVersion: v1

metadata:
  name:       static-assets
  namespace:  {{ .Release.Name }}
  labels:
    app:      static-web 

spec:
# It uses the standard DigitalOcean Starage Class - do-block-storage, 
# which supports RWO only
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.Static_assets.storage_size }}