kind:       Service
apiVersion: v1

metadata:
  name:       static-web-server
  namespace:  {{ .Release.Name }}

spec:
  type:  ClusterIP
  selector:
    app: static-web
  ports:
  - name:       static-web-port
    protocol:   TCP
    port:       8888
    targetPort: http
