kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: sample-app-scale
  namespace: {{ .Release.Name }}
  labels:
    app: django-sample

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: sample-app

  minReplicas: {{ .Values.Deployment.replicas.min }}
  maxReplicas: {{ .Values.Deployment.replicas.max }}

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.HPA.target.cpu }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.HPA.target.memory }}
