dyn_dns_passw: ENC[AES256_GCM,data:ca89B8QwTevvEPEaQsAA3gpqHzWODgUjZgk3Stda8LI=,iv:bAWxqLooAETuWMdbspfc4zvY2wEPMFxuoGJhw7umK9k=,tag:fNmCqOQHRk2HgnvkhsthkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-11-15T10:24:42Z"
    mac: ENC[AES256_GCM,data:T3muXcRO8pvi9SYygYQ2hgdZEHjWMYuUjS3mWhBn2APSraCSSzMWazBsiEriZcKfvtluYDEVMLbADt4JgJR4QZZqK4BrfyZ4GF1iaYaYtdGzQQrDkwpTd14KlY8rZEVfZOLGbRyrwgzOURJGUmJ8G9Gullv0Mvu0TVl39uZnq84=,iv:FPrSAzKbSHgKt9t+hjxnIy9LHMrxgHXoT4/fMuuOz78=,tag:aXW3AEIsrTdS1l70tFeRvg==,type:str]
    pgp:
        - created_at: "2023-11-15T10:23:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA7EfTLRKYejpAQgAgORCAKKZdnHg01bc5XwuKGyZKqEGQwZm1h6lmH5GE1RL
            kZdkIZequZKMrjS2DUrZm5JSATfmtNUb1SYePT+u4KopXt4p9ZFbfrP83gz4Bwk5
            cQwi4XYGtMsXRvdAGcgA6t1CdMXaYtZ9fSpUXL6/WlPlnswbmqT2N5nv2Pw5vb5Q
            7WEouhP6S7KGanE7JwmDSLHQ13RVE/fDgIEj5/M/ePfvTV6GP4xOfcF62UVzocoY
            XqsViXAY97Ahz3zw1IHBhn55neTPrtgt6MdLrATJG3ERngIox1XlhiZyDvW/Jwwi
            R3jqD/0pObLn5An7ZhXoUVGu0khmyV0M5NluhgnVL9JRAe/729a2bGZCrud3n3ou
            CMVR1iWSx4Xzr0hqlt58RMmaB0ELzwWE83hwJ//7md8b/030gAtYcb4RPYM7LNx9
            3zgZPvBNQlGsA6P0+/vttS33
            =oNLe
            -----END PGP MESSAGE-----
          fp: 57CB9AC86D23218AE4C9DF47365F1D249528952D
    unencrypted_suffix: _unencrypted
    version: 3.8.1
