formatter: "markdown table"

version: ""

header-from: "main.tf"
footer-from: ""

recursive:
  enabled: false
  path: modules  

sections:
  show:
    - header
    - providers
    - resources
    - requirements
    - inputs
    - outputs

content: |-
  {{ .Header }}
  ### Example

  ```hcl
  {{ include "examples/example-1/main.tf" }}
  ```
  ### Reference
  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Modules }}
  {{ .Outputs }}
  {{ .Resources }}

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->


output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 4
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
