kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2

metadata:
  name: sample-app-scale
  namespace: django-app
  labels:
    app: django-sample

spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: sample-app

  minReplicas: 2
  maxReplicas: 6

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
