kind: Issuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsincrypt-prod
  namespace: django-app

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: dmitry.fedunets@gmail.com
    privateKeySecretRef:
      name: letsincrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
