{{- include "default-deny.npol" . | nindent 0 }}

---

kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-allow-from-app
  namespace: {{ .Release.Name }}
spec:
  policyTypes:
    - Ingress

  podSelector: {}
  
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: django-sample
