kind: ServiceAccount
apiVersion: v1
metadata:
  name: sa-db
  namespace: {{ .Release.Name }}

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: db-credentials-2-db
  namespace: {{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: sa-db
  apiGroup: ""
roleRef:
  kind: Role
  name: db-credentials-reader
  apiGroup: rbac.authorization.k8s.io